config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # get 'partner', to: 'pages#partner'

  devise_for :users

  resources :partners do
    resources :products
    # resources :orders
    member do
      get :counter
    end
  end

  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]

    member do
      patch :consume
    end
  end

  resources :users, only: [:show, :edit, :update]

  resources :products, only: [] do
    member do
      get :generate_order
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  validates :name, presence: true
  validates :address, presence: true
  has_many :products
  has_many :orders, through: :products
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show, :edit, :update, :destroy, :counter]
  before_action :set_user, only: [:new, :create, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  layout "no_navigation", only: [:counter]

  def index

    @partners = Partner.all.includes(:products)

    if params[:city].present?
      @partners = @partners.near(params[:city], 15)
      cookies.permanent[:city] = params[:city]
    elsif params[:lat].present?
      @partners = @partners.near([params[:lat], params[:long]], 15)
    elsif cookies[:city].present?
      @partners = @partners.near(cookies[:city], 15)
    else
      @partners
    end
    set_markers
    # set_orders_status
  end

  def counter
    set_partner
    set_orders_status
  end

  def show
    @marker = {
        lng: @partner.longitude,
        lat: @partner.latitude
      }

    @products = Product.where(partner: @partner)
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    @product = Product.new(name: "café suspendu", price_cents: 200)
    @partner.user = current_user
    if @partner.save
      @product.partner = @partner
      @product.save
      redirect_to edit_partner_path(@partner)
    else

      render :new
    end
  end

  def edit
    if @partner.user == current_user
      set_orders_status
      @order = @partner.orders.where(consumed: false, state: "paid").first
    else
      redirect_to partners_path, :flash => { error: "You cant access this coffe" }
    end
  end

  def update
    if @partner.update!(partner_params)
      redirect_to partner_path(@partner)
    else
      render :edit
    end
  end

  def destroy
    @partner.destroy
    redirect_to partners_path
  end

private

  def set_markers
    @markers = @partners.map do |partner|
      {
        lng: partner.longitude,
        lat: partner.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { partner: partner }),
        partnerId: partner.id,
      }
    end
  end

  def set_partner
    @partner = Partner.find(params[:id])
  end

  def set_orders_status
    @orders_pending = @partner.orders.where(consumed: false, state: "paid").count
    @orders_total = @partner.orders.all.count
  end

  def set_user
    @user = current_user
  end

  def partner_params
    params.require(:partner).permit(:name, :address, :photo, :photo_cache)
  end
end

app/views/partners/_form.html.erb
  <%= simple_form_for @partner do |f| %>

<!--- Start banner --->
  <div class="banner-create-partner">
    <div class="">
      <h1>Devenez café partenaire</h1>
      <br>
      <p>rejoignez le mouvement Sospeso</p>
    </div>
  </div>
<!--- End banner --->


<div class="main-form-container">


  <!--- Start form --->
  <div class="form-container">
    <div>
      <%= f.input :name, label: "Nom de votre établissement", placeholder: "Le café du coin"  %>
    </div>
    <div>
      <%= f.input :address, label: "Adresse", placeholder: "11 rue des Cyprès, 69007 Lyon" %>
    </div>
    <div>
      <%= f.input :description, label: "Un petit mot sur votre café :", placeholder: "Description" %>
    </div>



    <div class="partner-form-container">
      <div class="partner-imgup">
        <p>Une photo de votre café</p>
      </div>
      <div class="img-picto">
        <i class="fas fa-camera-retro"></i>
      </div>
      <div>
        <%= f.file_field :photo %>
      </div>
      <div class="btn-partner">
        <%= f.submit "Rejoindre la communauté des cafés solidaires", class: "btn-ghost-white" %>
      </div>
    </div>
    <% end %>
  </div>

  <!--- End form --->

  <!--- Start information --->
  <div class="info-container">
    <div class="info-icon">
      <i class="fas fa-coffee"></i>
    </div>
    <div class="info-title">
      <h3>Vous rejoignez le mouvement Sospeso ?</h3>
    </div>
    <div class="info-description">
      <p>
        La tradition du café suspendu a commencé à Naples. Quand un Napolitain se sent heureux, il commande deux cafés et il n'en boit qu'un seul : le second est en attente, inscrit sur une ardoise comme café suspendu pour un client qui n'aura pas les moyens de se le payer. Depuis, cet acte de solidarité s'est répandu dans près de 140 villes du monde entier. L'idée a déjà trouvé une place au comptoir de plusieurs restos-cafés en France. On allonge la liste ? :)
      </p>
    </div>
  </div>
  <!--- End information --->

</div>

app/views/partners/_infowindow.html.erb
<strong><%= partner.name %></strong>
<p>
<%= partner.address %>
</p>
<br>
<%= link_to "Voir ce café", partner_path(partner)%>
<br>
<br>

app/views/partners/counter.html.erb
<div class="background-counter">

<!-- Start counter -->
      <div class="counter">
        <div id="tens" class="flipper">
        <%= (@orders_pending - (@orders_pending % 10))/10 %>
        </div>
        <div id="ones" class="flipper"><%= (@orders_pending % 10) %>
        </div>
      </div>
<!-- End counter -->
      <div class="pending-coffees">
    <h1>café(s) suspendu(s)</h1>
  </div>
<!-- Start text counter -->
   </div>

<!-- End text counter -->

  </div>
</div>

      <p><%= content_for @orders_pending %></p>
    <% content_for :after_js do %>
      <script>
          App['partner_counter_#{@partner.id}'] = App.cable.subscriptions.create({
            channel: 'PartnerCountersChannel',
            counter_partner_id: <%= @partner.id %>
          }, {
            received: (data) => {
                // console.log(data)
              const count = document.getElementById('counter')
              const one = (data.toto % 10)
              const ten = ((data.toto - one)/10)
              console.log(one)
              console.log(ten)
              const ones = document.getElementById('ones')
              const tens = document.getElementById('tens')
              console.log(ones.textContent.value)
              ones.textContent = one
              tens.textContent = ten
              playSound();
            }
          });

          function playSound() {
            var snd = new Audio("https://www.myinstants.com/media/sounds/y2mate_HPejngs.mp3");
              snd.play();
          }
      </script>
    <% end %>

<script>
    /* --------------------
     Add your code here
    --------------------- */

    const ones = document.querySelector('#ones');
    const tens = document.querySelector('#tens');

    function count() {
      const date = new Date();
      const secs = date.getSeconds();
      // const arrayClock = (secs / 10).toString().split('.');

      // tens.textContent = arrayClock[0];
      // ones.textContent = arrayClock[1] || 0;

      // why doesn't textContent or innerHTML work here, but innerText does?
      // I BELIEVE this is because DOMCharacterDataModified is not picking it up?
      // So let's test this once we get MutationObserver in place!
      // ...Yuo! That's what it was, and now when using MutationObserver, textContent works
    }

    function flip(elem) {
      elem.classList.contains('flip') ? elem.classList.remove('flip') : elem.classList.add('flip');
    }

    function observeNumbers (mutationsList, observer) {
      for (let mutation of mutationsList) {
        if (mutation.type === 'childList') {
          flip(mutation.target)
        }
      }
    }

    const obeserveConfig = {
      attributes: true,
      childList: true,
      subtree: true
    }

    const observer = new MutationObserver(observeNumbers);
    observer.observe(ones, obeserveConfig)
    observer.observe(tens, obeserveConfig)

    /*
    DONT USE DOMCharacterDataModified
    USE MutationObserver instead!

    ones.addEventListener('DOMCharacterDataModified', (e) => {
      // console.log(e);
      // console.log(e.prevValue);
      // console.log(e.newValue);
      // console.log(e.target);
      flip(e.srcElement.parentElement)
    });


    tens.addEventListener('DOMCharacterDataModified', (e) => {
       if (!e.prevValue === e.newValue) {
         flip(e.srcElement.parentElement)
       }
    });
    */

    setInterval(count, 1000);
</script>

app/views/partners/edit.html.erb
<!--- Start banner --->
  <div class="banner-edit-partner">
    <div class="">
      <h1>Paramètres</h1>
      <br>
      <p>Accédez à la mise à jour des informations de votre établissement et au nombre de Sospesos disponibles.</p>
    </div>
  </div>
<!--- End banner --->

<%= simple_form_for @partner do |f| %>

<div class="main-coffee-container">

  <div class="form-placement">
    <div class="form-partner-container">

      <div>
        <%= f.input :name, label: "Nom de votre établissement", placeholder: "Le café du coin"  %>
      </div>
      <div>
        <%= f.input :address, label: "Adresse", placeholder: "11 rue des Cyprès, 69007 Lyon" %>
      </div>
      <div>
        <%= f.input :description, label: "Un petit mot sur votre café :", placeholder: "Description" %>
      </div>

      <div class="partner-form-container">
        <div class="partner-imgup">
          <p>Une photo de votre café</p>
        </div>
        <div class="img-picto">
          <%= cl_image_tag @partner.photo, width: 400, height: 150, crop: :fill %>
        </div>
        <div>
          <%= f.file_field :photo %>
        </div>
        <div class="btn-partner">
          <%= f.submit "Mettre à jour les informations", class: "btn-ghost" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="coffee-space">
    <div class="status-space">
      <p> Vous avez actuellement </p>
      <br>
      <div class="instant-count">
      <p  id="counter"><%= @orders_pending %></p>
      </div>
      <br>
      <p>Sospeso(s) en attente</p>
    </div>
    <div>
      <div class="coffee-partner-served">
        <%= render 'shared/orderbutton', order: @order %>
      </div>
      <div class="coffee-all">
        <%= link_to "Mon compteur display", counter_partner_path, class: "btn-partner-count"  %>
      </div>

      <%= simple_form_for @partner do |f| %>

        <% if @partner.errors.any? %>
        <div class="errors-container">
          <ul>
            <% @partner.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>

</div>
<% content_for :after_js do %>
  <script>
      App['partner_counter_#{@partner.id}'] = App.cable.subscriptions.create({
        channel: 'PartnerCountersChannel',
        counter_partner_id: <%= @partner.id %>
      }, {
        received: (data) => {
          console.log(data)
        const count = document.getElementById('counter')
        console.log(count.innerHTML)
        count.innerHTML = data.toto
        }

      })
  </script>
<% end %>

app/views/partners/index.html.erb
<div class="main-container">

  <div class="partner-banner">
    <div class="partner-container">
      <div class="title-wrapper">
        <h1>Les cafés partenaires</h1>
      </div>
    </div>
  </div>


  <div class= "second-container">

<!-- début du html pour lindex des partners -->

    <div class="partners-list-container">

      <div class="search-bar-container">
        <div>
          <%= form_tag partners_path, method: :get do %>
            <div id="input-styling-address">
              <input type="search" id="input-algo" name="city" class="partner-search-bar" placeholder="Cherchez une adresse">
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <% @partners.each do |partner| %>
          <div class="col-sm-12 col-md-12 col-lg-12">

            <a href="#" class="show-toogle" data-partner-id="<%= partner.id %>">

              <div class="partner-card">
                <div class="partner-img" style="background-image: linear-gradient(to left, rgba(71, 71, 71, .2), rgba(71, 71, 71, .4)), url('<%= cl_image_path partner.photo %>'); ">
                </div>
                <div class="partner-name">
                  <h3><%= partner.name %></h3>
                </div>
                <div class="partner-address">
                  <p><i class="fas fa-map-marker-alt"></i><%= partner.address %></p>
                </div>

                <div class="coffee-status">
                  <div class="coffee-pending">
                    <div class="pending">
                      <p> <%= partner.orders.where(consumed: false, state: 'paid').count %></p>
                    </div>
                  </div>
                  <div class="dispo">
                    <p>Sospeso(s) disponible(s) ici</p>
                  </div>
                </div>

                <div class="partner-btn">
                  <i class="fas fa-search"></i>
                </div>
              </div>
            </a>
          </div>
        <% end %>
      </div>

    </div>

<!-- début du html pour le show du partner -->

    <div id="show">
      <% @partners.each do |partner| %>
        <div class="info-partner hidden" id="info-partner-<%= partner.id%>" data-partner-id="<%= partner.id %>">

          <div class="info-partner-img" style="background-image: linear-gradient(to left, rgba(71, 71, 71, .1), rgba(71, 71, 71, .3)), url('<%= cl_image_path partner.photo %>'); ">
          </div>
          <div class="info-partner-name">
            <h3><%= partner.name %></h3>
          </div>
          <div class="info-partner-desc">
            <p><i class="fas fa-map-marker-alt"></i><%= partner.address %></p>
          </div>
          <div class="bref">
            <p><%= partner.description %></p>
          </div>

          <div class="coffee-status-bis">
            <div class="coffee-pending-bis">
              <div class="pending-bis">
                <p><%= partner.orders.where(consumed: false, state: 'paid').count %></p>
              </div>
            </div>
            <div class="dispo">
              <p>Sospeso(s) disponible(s) chez </br><%= partner.name %></p>
            </div>
          </div>

          <br>

          <div class="coffee-after">
            <div class="coffee-after-bis">
              <div class="after-bis">
                <p><%= partner.orders.where(consumed: true).count %></p>
              </div>
            </div>
            <div class="dispo">
              <p>Sospeso(s) déjà servi(s)</p>
            </div>
          </div>

          <div class="offer">
            <div class="offer-btn">
              <% if partner.products.present? %>


                <%= link_to generate_order_product_path(partner.products.first.id), class: 'btn-offer-coffee' do %>
                  <i class="fas fa-coffee"></i>Offrir un café ici
                <% end %>

              <% end %>
            </div>
          </div>

          <div class="edit-container">
            <div class="edit-placement">
              <div>
                <% if partner.user == current_user %>
                <div class="edit-text">
                  <p>Ce café vous appartient !</p>
                </div>
                  <%= link_to 'Modifier la fiche', edit_partner_path(partner), :class=>"edit-btn" %>
                <% end %>
              </div>
            </div>
          </div>


        </div>
      <% end %>
    </div>

    <!-- début du html pour la sticky map-->

    <div class="map-container">
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="map-wrapper">
          <div id="map" data-markers="<%= @markers.to_json %>">
          </div>
        </div>
      </div>
    </div>

  </div>
</div>


<% content_for :after_js do %>
   <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js">
    </script>
  <script type="text/javascript" src="https://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_KEY']%>&callback=initMap" async defer></script>
<% end %>

app/views/partners/new.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger text-center" id="flash" role="alert"><%= flash[:error] %></div>
<% end %>

<%= render 'form', partner: @partner %>

app/views/partners/show.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger text-center" id="flash" role="alert"><%= flash[:error] %></div>
<% end %>


<!--- Start banner --->
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= photo_path_for(@partner)%>)">
        <div class="container">
          <h1><%= @partner.name %></h1>
          <p><%= @partner.address %></p>
        </div>
      </div>
<!--- End banner --->


<% if @partner.user == current_user %>
  <%= link_to 'Modifier', edit_partner_path %>
<% end %>
<!--
<%= link_to 'Supprimer le café partenaire', partner_path(@partner), method: :delete %>
 -->

<div class="container" id=partner-detail>
<div>
  <br>
  <%= link_to "Retour à la liste", partners_path, :class=>"btn btn-ghost" %>
</div>
<br>
<h2>Offrir un café</h2>

<ul>
    <% @partner.products.each do |product| %>
    <li>
      <%= product.name %> - <%= product.price %>
    </li>
    <li>
      Il y a <%= product.orders.size %> café(s) actuellement suspendu(s) à <%= @partner.name %>
    </li>
      <%= form_tag orders_path do %>
        <%= hidden_field_tag 'teddy_id', product.id %>
        <br>
        <%= submit_tag 'Offrir un café', class: 'btn-ghost' %>
      <% end %>
    <% end %>
</ul>
</div>


<h3>Mon café partenaire</h3>
<!--The div element for the map -->
<div id="map" data-markers="<%= [@marker].to_json %>"></div>
<!-- Replace the value of the key parameter with your own API key. -->

<% content_for :after_js do %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_KEY']%>&callback=initMap" async defer></script>
<% end %>