config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # get 'partner', to: 'pages#partner'

  devise_for :users

  resources :partners do
    resources :products
    # resources :orders
    member do
      get :counter
    end
  end

  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]

    member do
      patch :consume
    end
  end

  resources :users, only: [:show, :edit, :update]

  resources :products, only: [] do
    member do
      get :generate_order
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- start footer-section -->
<div class="footer">
    <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
    <div class="footer-copyright">
      <p>App réalisée avec beaucoup de <i class="fas fa-heart"> </i> et de <i class="fas fa-coffee"> </i> au <a href="https://www.lewagon.com/fr/lyon">Wagon</a> </p>
    </div>
</div>
<!-- /end footer-section -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://res.cloudinary.com/di985lta5/image/upload/v1551704596/sospeso.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Link when logged in -->
      <div>
        <%= link_to "Devenez partenaire", new_partner_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>

      <!-- Profile with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <a class="navbar-wagon-item navbar-wagon-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon compte</a>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mon compte") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path(current_user.id) do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Paramètres") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "S'inscrire"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'Devenez partenaire', new_partner_path %></li>
        <li><%= link_to 'Se connecter', new_user_session_path %></li>
        <li><%= link_to "S'inscrire", new_user_registration_path %></li>
        <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_orderbutton.html.erb
       <% unless order.nil? %>
          <%= link_to "1 Sospeso(s) servi", consume_order_path(order), remote: true, method: :patch, class: "btn-partner-served" %>
        <% end %>