config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # get 'partner', to: 'pages#partner'

  devise_for :users

  resources :partners do
    resources :products
    # resources :orders
    member do
      get :counter
    end
  end

  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]

    member do
      patch :consume
    end
  end

  resources :users, only: [:show, :edit, :update]

  resources :products, only: [] do
    member do
      get :generate_order
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @order.amount_cents,
      description:  "Payment for Product #{@order.product_id} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    ActionCable.server.broadcast(
      "partner_counter_#{@order.product.partner.id}",
      toto: @order.product.partner.orders.where(consumed: false, state: 'paid').count
    )
    redirect_to order_path(@order)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    # if current_user.present?
      @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    # else
    #   cookies.permanent[:coucou] = "coucou"
    #   raise
    # end
  end
end

app/views/payments/new.html.erb
<div class="main-payment-container">
  <div class="payment-container">
    <div class="payment-img" style="background-image:url('<%= cl_image_path @order.product.partner.photo %>');">
    </div>
    <div class="payment-title">
      <h2>Offrir un Sospeso <br> chez <%= @order.product.partner.name %></h2>
      <p><%= @order.product.partner.name %> recevra automatiquement votre participation et mettra à disposition le Sospeso dans son établissement.</p>
    </div>
    <!-- div pour créer un espace  -->
    <div class="espace-place">
    </div>
    <!-- div pour créer un espace  -->
    <div class="payment-description">
      <%= form_tag order_payments_path(@order) do %>
      <div class="payment-price">
        <article>
          <label class="amount">
            <p>Prix solidaire :</p>
            <div class="fair-price">
              <p>
                <%= humanized_money_with_symbol(@order.amount) %>
              </p>
            </div>
          </label>
        </article>
      </div>
      <!-- div pour créer un espace  -->
      <div class="espace-place">
      </div>
      <!-- div pour créer un espace  -->
      <div class="payment-btn">
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-name="J'offre un Café"
        data-email="<%= current_user.email %>"
        data-description="Café suspendu chez <%= @order.product.partner.name %>"
        data-amount="<%= @order.amount_cents %>"
        data-currency="<%= @order.amount.currency %>"></script>
      </div>
    <% end %>
    </div>
  </div>

</div>