config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # get 'partner', to: 'pages#partner'

  devise_for :users

  resources :partners do
    resources :products
    # resources :orders
    member do
      get :counter
    end
  end

  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]

    member do
      patch :consume
    end
  end

  resources :users, only: [:show, :edit, :update]

  resources :products, only: [] do
    member do
      get :generate_order
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :partner
  has_many :orders
  monetize :price_cents
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def generate_order
    product = Product.find(params[:id])
    order   = Order.create!(product: product, amount: product.price, state: 'pending', user: current_user)
    redirect_to new_order_payment_path(order)
  end
end

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <h1>Products</h1>
    <% @products.each do |product| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= link_to image_tag(product.photo_url), product_path(product) %>
          <div class="caption">
            <h3><%= link_to product.name, product_path(product) %></h3>
            <p><%= product.name %></p>
            <p>$$$</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @product.name %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6">
<!--       <%= image_tag(@product, width: '100%') %> -->
    </div>
    <div class="col-sm-12 col-md-6">
      <p>Some awesome description of our amazing product.</p>
      <p>$$$</p>
    </div>
  </div>
</div>